kraken:
    kubeconfig_path: /var/lib/jenkins/.kube/config                 # Path to kubeconfig
    exit_on_failure: False                 # Exit when a post action scenario fails
    chaos_scenarios:                           # List of policies/chaos scenarios to load
        -   pod_scenarios:
              - -    scenarios/regex_openshift_pod_kill.yml
cerberus:
    cerberus_enabled: True               # Enable it when cerberus is previously installed
    cerberus_url: http://52.224.144.215:8080                       # When cerberus_enabled is set to True, provide the url where cerberus publishes go/no-go signal

tunings:
    wait_duration: 60                     # Duration to wait between each chaos scenario
    iterations: 1                           # Number of times to execute the scenarios
    daemon_mode: False                         # Iterations are set to infinity which means that the cerberus will monitor the resources forever
