---
- hosts: localhost
  gather_facts: true
  vars_files:
   - vars/kraken_vars.yml

  tasks:
  - name: Git clone kraken repository
    git:
      repo: "{{ kraken_repository }}"
      dest: "{{ kraken_dir }}"
      force: yes

  - name: Generate kraken config file
    template:
      src: kraken.j2
      dest: "{{ kraken_config }}"

  - name: Start injecting failures
    shell: |
      cd "{{ kraken_dir }}"
      cp -r "{{ scenarios_folder_path }}"* scenarios/
      unset CONFIG
      python3 run_kraken.py
    ignore_errors: yes
